### PR TITLE
Fixed meta command summaries

### PR DESCRIPTION
**Pull request by gabriel-barrett**

### CODE REVIEW

**Comment by arthurpaulino** [comment]
Thanks! But this is not following the documentation model from other commands. The summary would say something like "Retrieves the current state from a microchain ...". The return is already specified in the "return" field

**Comment by gabriel-barrett** [comment]
> Thanks! But this is not following the documentation model from other commands. The summary would say something like "Retrieves the current state from a microchain ...". The return is already specified in the "return" field

I understand the use of retrieve, as it retrieves data from the web, but return has a very specific meaning, that of the return value of the metacommand when used inside an expression. I would rather update the comment to "retrieve and return".

**Comment by arthurpaulino** [comment]
All meta commands return something. If we describe all of them as "Returns ...", it's going to be an annoyance for what `!(help)` prints

**Comment by gabriel-barrett** [comment]
> All meta commands return something. If we describe all of them as "Returns ...", it's going to be an annoyance for what `!(help)` prints

Yes, but you're proposing I change the name to "retrieve" only so it's a different word, as to not look repetitive. There's no reason to change any of the other summaries I believe. Most return values are pro forma, and not really relevant, and in a few cases the return value is of limited utility, used in a few cases. In this instance, the return value is integral

**Review by arthurpaulino — APPROVED** [review]
I agree. You've convinced me.
Thanks for the patch!

**Pull request merged**
